# Generated by Django 5.2.8 on 2026-05-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_posts_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at'], 'verbose_name': 'پست ها ', 'verbose_name_plural': 'پست '},
        ),
    ]
